FROM amazonlinux:2.0.20201111.0																																																											
RUN yum -y update && yum -y install https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm																																																											
RUN yum install amazon-cloudwatch-agent																																																											
COPY config/config.json /etc/cwagentconfig																																																											
COPY config/config.json /opt/aws/amazon-cloudwatch-agent/bin/																																																											
ENV RUN_IN_CONTAINER="True"																																																											
ENTRYPOINT ["/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent"]																																																											


